## Assignment-5 — NumPy Introduction-1

**Roll No:** 1024170446  
**Name:** Paryag Bansal

## Q1 — 1D array basic ops

In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print("Original:", arr)
print("Add 2:", arr + 2)
print("Multiply 3:", arr * 3)
print("Divide by 2:", arr / 2)

Original: [10 20 30 40 50]
Add 2: [12 22 32 42 52]
Multiply 3: [ 30  60  90 120 150]
Divide by 2: [ 5. 10. 15. 20. 25.]


## Q2 — Reverse & most frequent

In [2]:
arr = np.array([1, 2, 3, 6, 4, 5])
print("Reversed:", arr[::-1])

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
vals, counts = np.unique(x, return_counts=True)
most = vals[np.argmax(counts)]
print("x most frequent:", most, "at indices", np.where(x == most)[0])

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
vals, counts = np.unique(y, return_counts=True)
most = vals[np.argmax(counts)]
print("y most frequent:", most, "at indices", np.where(y == most)[0])

Reversed: [5 4 6 3 2 1]
x most frequent: 1 at indices [0 5 7 8 9]
y most frequent: 1 at indices [0 1 2]


## Q3 — 2D indexing

In [3]:
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])
print("1st row, 2nd col:", arr[0, 1])
print("3rd row, 1st col:", arr[2, 0])

1st row, 2nd col: 20
3rd row, 1st col: 70


## Q4 — linspace array named after you

In [4]:
paryag = np.linspace(10, 100, 25)
print("paryag:", paryag)
print("ndim:", paryag.ndim)
print("shape:", paryag.shape)
print("size:", paryag.size)
print("dtype:", paryag.dtype)
print("nbytes:", paryag.nbytes)

# transpose via reshape (1D -> column vector)
print("\nreshape to column:\n", paryag.reshape(25, 1))

# T on 1D does nothing useful — stays 1D
print("\n.T on 1D:", paryag.T)
print("T only really transposes 2D+ arrays")

paryag: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
ndim: 1
shape: (25,)
size: 25
dtype: float64
nbytes: 200

reshape to column:
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]

.T on 1D: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
T only really transposes 2D+ arrays


## Q5 — 2D array stats, reshape, resize

In [5]:
ucs420_paryag = np.array([[10, 20, 30, 40],
                         [50, 60, 70, 80],
                         [90, 15, 20, 35]])
print("ucs420_paryag:\n", ucs420_paryag)
print("mean:", np.mean(ucs420_paryag))
print("median:", np.median(ucs420_paryag))
print("max:", np.max(ucs420_paryag))
print("min:", np.min(ucs420_paryag))
print("unique:", np.unique(ucs420_paryag))

reshaped_ucs420_paryag = ucs420_paryag.reshape(4, 3)
print("\nreshaped (4x3):\n", reshaped_ucs420_paryag)

resized_ucs420_paryag = np.resize(ucs420_paryag, (2, 3))
print("\nresized (2x3):\n", resized_ucs420_paryag)

ucs420_paryag:
 [[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
mean: 43.333333333333336
median: 37.5
max: 90
min: 10
unique: [10 15 20 30 35 40 50 60 70 80 90]

reshaped (4x3):
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

resized (2x3):
 [[10 20 30]
 [40 50 60]]
