## Assignment 6 — Numpy-II

**Roll No:** 1024170446  
**Name:** Paryag Bansal

## Q1 — Sensor readings (vectorization)

In [1]:
import numpy as np

temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])
print("Original:", temperature)

# a. add 2°C
corrected = temperature + 2
print("After +2°C:", corrected)

# b. C to F
fahrenheit = (9/5) * temperature + 32
print("Fahrenheit:", fahrenheit)

# c. readings > 32
hot = temperature[temperature > 32]
print("Above 32°C:", hot)

# d. count
print("Count above 32°C:", np.sum(temperature > 32))

# e. vectorization & boolean indexing skip python loops —
# numpy does the work in compiled C, so large arrays stay fast

Original: [25 28 31 35 38 27 33 40]
After +2°C: [27 30 33 37 40 29 35 42]
Fahrenheit: [ 77.   82.4  87.8  95.  100.4  80.6  91.4 104. ]
Above 32°C: [35 38 33 40]
Count above 32°C: 4


## Q2 — Daily steps matrix

In [2]:
steps = np.array([
    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]
])
print("steps:\n", steps)

print("Total steps:", np.sum(steps))
print("Mean steps:", np.mean(steps))
print("Max:", np.max(steps), "Min:", np.min(steps))
print("Total per day (axis=0):", np.sum(steps, axis=0))
print("Total per user (axis=1):", np.sum(steps, axis=1))

# argmax gives flat index; unravel to (user, day)
flat_idx = np.argmax(steps)
pos = np.unravel_index(flat_idx, steps.shape)
print("Max at user/day:", pos, "value:", steps[pos])

steps:
 [[5000 6200 7100]
 [8000 7500 9000]
 [4500 5100 4800]
 [9000 8500 9500]]
Total steps: 84200
Mean steps: 7016.666666666667
Max: 9500 Min: 4500
Total per day (axis=0): [26500 27300 30400]
Total per user (axis=1): [18300 24500 14400 27000]
Max at user/day: (3, 2) value: 9500


## Q3 — Slicing, views, reshape, flatten vs ravel

In [3]:
original = np.array([1, 2, 3, 4, 5, 6])
print("original:", original)

# b. slice index 1 to 4
subset = original[1:5]
print("subset:", subset)

# c. modify subset (view) — original changes too
subset[0] = 999
print("After subset[0]=999")
print("original:", original)
print("subset:", subset)

# d. copy — original stays safe
original = np.array([1, 2, 3, 4, 5, 6])  # reset
copied = original[1:5].copy()
copied[0] = 500
print("\nAfter copy modify")
print("original:", original)
print("copied:", copied)

# e. arange + reshape
mat = np.arange(1, 13).reshape(3, 4)
print("\n3x4 matrix:\n", mat)

# f. extractions
print("First row:", mat[0])
print("Last row:", mat[-1])
print("Second column:", mat[:, 1])
print("Rows 1-2, cols 2-3:\n", mat[1:3, 2:4])

# g. flatten vs ravel
flat = mat.flatten()
rav = mat.ravel()
print("\nflatten():", flat)
print("ravel():", rav)

# h. ravel is a view — original can change
rav[0] = 100
print("After ravel[0]=100, matrix:\n", mat)

# i. flatten is a copy — original stays
mat = np.arange(1, 13).reshape(3, 4)  # reset
flat = mat.flatten()
flat[0] = 200
print("After flatten[0]=200, matrix:\n", mat)

# j. attributes
print("shape:", mat.shape)
print("ndim:", mat.ndim)
print("size:", mat.size)
print("dtype:", mat.dtype)

original: [1 2 3 4 5 6]
subset: [2 3 4 5]
After subset[0]=999
original: [  1 999   3   4   5   6]
subset: [999   3   4   5]

After copy modify
original: [1 2 3 4 5 6]
copied: [500   3   4   5]

3x4 matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
First row: [1 2 3 4]
Last row: [ 9 10 11 12]
Second column: [ 2  6 10]
Rows 1-2, cols 2-3:
 [[ 7  8]
 [11 12]]

flatten(): [ 1  2  3  4  5  6  7  8  9 10 11 12]
ravel(): [ 1  2  3  4  5  6  7  8  9 10 11 12]
After ravel[0]=100, matrix:
 [[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
After flatten[0]=200, matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
shape: (3, 4)
ndim: 2
size: 12
dtype: int32


## Q4 — OLS regression for assistance score

In [4]:
X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]
])
y = np.array([40, 65, 30, 85])

print("X shape:", X.shape, "ndim:", X.ndim)

# b. transpose — features become rows, users become columns
print("X.T:\n", X.T)

# c. X.T @ X
XtX = X.T @ X
print("X.T @ X:\n", XtX)

# d. inverse
XtX_inv = np.linalg.inv(XtX)
print("inv(X.T @ X):\n", XtX_inv)

# e. beta = (X.T X)^-1 X.T y
beta = XtX_inv @ X.T @ y
print("coefficients beta:", beta)

# f. beta[0] = weight for sleep hours
#    beta[1] = weight for activity level
#    beta[2] = weight for stress level
# positive weight → higher feature pushes score up, negative → pulls it down

# g. predict for new user
new_user = np.array([5, 40, 7])
pred = new_user @ beta
print("Predicted assistance score:", pred)

X shape: (4, 3) ndim: 2
X.T:
 [[ 6  5  8  4]
 [70 50 80 30]
 [ 3  6  2  8]]
X.T @ X:
 [[  141  1430    96]
 [ 1430 14700   910]
 [   96   910   113]]
inv(X.T @ X):
 [[ 1.10521428 -0.09848746 -0.14581398]
 [-0.09848746  0.00891203  0.01190129]
 [-0.14581398  0.01190129  0.0368847 ]]
coefficients beta: [-0.15921454  0.14083853 10.06302242]
Predicted assistance score: 75.27862544779117
